
title: My Resume
url: 'https://pluanvo.github.io/'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Luan Vo  ## put your name
title: 'NETWORK &amp; SYSTEM ADMIN'  ## your title
location: Da Nang - Viet Nam


## Social Profiles
facebook: https://www.facebook.com/phuc.luan.1  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
#linkedin: http://www.linkedin.com  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
