
title: My Resume
url: 'https://pluanvo.github.io/'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Luan Vo  ## put your name
title: 'NETWORK &amp; SYSTEM ADMIN'  ## your title
location: Da Nang - Viet Nam


## Social Profiles
facebook: http://www.facebook.com/phuc.luan.1  ## your facebook account url
twitter: http://twitter.com/LunV31715600 ## your twitter account url
linkedin: http://www.linkedin.com/in/pluanvo  ## your linkedin account url
dribbble: https://pluanvo.github.io/ ## you dribbble account url
foursquare: https://pluanvo.github.io/ ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
